import Database from 'better-sqlite3';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { id, timestamp } from '../../core/src/index.js';
import type { FederationMessage, FederationOutboxRecord, InboxRecord, InboxStore, OutboxStatus, OutboxStore } from './types.js';

type OutboxRow = { id: string; message_id: string; destination: string; payload_json: string; attempts: number; next_attempt_at: number; created_at: string; status: OutboxStatus; last_error: string | null; idempotency_key: string };
type InboxRow = { message_id: string; idempotency_key: string; received_at: string; status: InboxRecord['status']; attempts: number; last_error: string | null };

export class SqliteOutboxStore implements OutboxStore {
  private readonly db: Database;
  constructor(file: string) { mkdirSync(dirname(file), { recursive: true }); this.db = new Database(file, { timeout: 5_000 }); this.db.pragma('journal_mode = WAL'); this.db.pragma('synchronous = NORMAL'); this.db.exec('CREATE TABLE IF NOT EXISTS federation_outbox (id TEXT PRIMARY KEY, message_id TEXT NOT NULL UNIQUE, destination TEXT NOT NULL, payload_json TEXT NOT NULL, attempts INTEGER NOT NULL, next_attempt_at INTEGER NOT NULL, created_at TEXT NOT NULL, status TEXT NOT NULL, last_error TEXT, idempotency_key TEXT NOT NULL UNIQUE); CREATE INDEX IF NOT EXISTS idx_federation_outbox_pending ON federation_outbox(status, next_attempt_at);'); }
  close(): void { this.db.close(); }
  enqueue(input: FederationOutboxRecord | Omit<FederationOutboxRecord, 'id' | 'createdAt' | 'attempts' | 'nextAttemptAt' | 'status'> & { id?: string }): FederationOutboxRecord { const record: FederationOutboxRecord = { id: input.id ?? id('outbox'), messageId: input.messageId, destination: input.destination, payload: structuredClone(input.payload), attempts: 0, nextAttemptAt: Date.now(), createdAt: timestamp(), status: 'pending', idempotencyKey: input.idempotencyKey }; const existing = this.findByKey(record.messageId, record.idempotencyKey); if (existing) return existing; this.db.prepare('INSERT INTO federation_outbox (id,message_id,destination,payload_json,attempts,next_attempt_at,created_at,status,last_error,idempotency_key) VALUES (?,?,?,?,?,?,?,?,?,?)').run(record.id, record.messageId, record.destination, JSON.stringify(record.payload), record.attempts, record.nextAttemptAt, record.createdAt, record.status, null, record.idempotencyKey); return structuredClone(record); }
  claim(limit = 10, now = Date.now()): FederationOutboxRecord[] { const bounded = Math.max(1, Math.min(100, Math.floor(limit))); const rows = this.db.prepare("SELECT * FROM federation_outbox WHERE status IN ('pending','sending') AND next_attempt_at <= ? ORDER BY next_attempt_at, created_at LIMIT ?").all(now, bounded) as OutboxRow[]; const claimed: FederationOutboxRecord[] = []; for (const row of rows) { const result = this.db.prepare("UPDATE federation_outbox SET status = ?, attempts = attempts + 1 WHERE id = ? AND status IN ('pending','sending')").run('sending', row.id); if (result.changes) claimed.push(this.fromRow({ ...row, status: 'sending', attempts: row.attempts + 1 })); } return claimed; }
  ack(recordId: string): FederationOutboxRecord { return this.updateStatus(recordId, 'sent'); }
  retry(recordId: string, error: string, nextAttemptAt: number): FederationOutboxRecord { const result = this.db.prepare('UPDATE federation_outbox SET status = ?, next_attempt_at = ?, last_error = ? WHERE id = ?').run('pending', nextAttemptAt, error.slice(0, 500), recordId); if (!result.changes) throw new Error(`Unknown outbox record: ${recordId}`); return this.get(recordId); }
  deadLetter(recordId: string, error: string): FederationOutboxRecord { const result = this.db.prepare('UPDATE federation_outbox SET status = ?, last_error = ? WHERE id = ?').run('dead-letter', error.slice(0, 500), recordId); if (!result.changes) throw new Error(`Unknown outbox record: ${recordId}`); return this.get(recordId); }
  listPending(): FederationOutboxRecord[] { return (this.db.prepare("SELECT * FROM federation_outbox WHERE status IN ('pending','sending') ORDER BY next_attempt_at, created_at").all() as OutboxRow[]).map((row) => this.fromRow(row)); }
  listDeadLetters(): FederationOutboxRecord[] { return (this.db.prepare("SELECT * FROM federation_outbox WHERE status = 'dead-letter' ORDER BY created_at").all() as OutboxRow[]).map((row) => this.fromRow(row)); }
  count(status?: OutboxStatus): number { const row = status ? this.db.prepare('SELECT COUNT(*) AS count FROM federation_outbox WHERE status = ?').get(status) as { count: number } : this.db.prepare('SELECT COUNT(*) AS count FROM federation_outbox').get() as { count: number }; return row.count; }
  private get(recordId: string): FederationOutboxRecord { const row = this.db.prepare('SELECT * FROM federation_outbox WHERE id = ?').get(recordId) as OutboxRow | undefined; if (!row) throw new Error(`Unknown outbox record: ${recordId}`); return this.fromRow(row); }
  private updateStatus(recordId: string, status: OutboxStatus): FederationOutboxRecord { const result = this.db.prepare('UPDATE federation_outbox SET status = ? WHERE id = ?').run(status, recordId); if (!result.changes) throw new Error(`Unknown outbox record: ${recordId}`); return this.get(recordId); }
  private findByKey(messageId: string, idempotencyKey: string): FederationOutboxRecord | undefined { const row = this.db.prepare('SELECT * FROM federation_outbox WHERE message_id = ? OR idempotency_key = ? LIMIT 1').get(messageId, idempotencyKey) as OutboxRow | undefined; return row ? this.fromRow(row) : undefined; }
  private fromRow(row: OutboxRow): FederationOutboxRecord { return { id: row.id, messageId: row.message_id, destination: row.destination, payload: JSON.parse(row.payload_json) as FederationMessage, attempts: row.attempts, nextAttemptAt: row.next_attempt_at, createdAt: row.created_at, status: row.status, idempotencyKey: row.idempotency_key, ...(row.last_error ? { lastError: row.last_error } : {}) }; }
}

export class SqliteInboxStore implements InboxStore {
  private readonly db: Database;
  constructor(file: string) { mkdirSync(dirname(file), { recursive: true }); this.db = new Database(file, { timeout: 5_000 }); this.db.pragma('journal_mode = WAL'); this.db.pragma('synchronous = NORMAL'); this.db.exec('CREATE TABLE IF NOT EXISTS federation_inbox (message_id TEXT PRIMARY KEY, idempotency_key TEXT NOT NULL UNIQUE, received_at TEXT NOT NULL, status TEXT NOT NULL, attempts INTEGER NOT NULL, last_error TEXT); CREATE INDEX IF NOT EXISTS idx_federation_inbox_received ON federation_inbox(received_at);'); }
  close(): void { this.db.close(); }
  seen(messageId: string, idempotencyKey = messageId): boolean { const row = this.db.prepare('SELECT message_id FROM federation_inbox WHERE message_id = ? OR idempotency_key = ? LIMIT 1').get(messageId, idempotencyKey) as { message_id: string } | undefined; if (row) { this.db.prepare('UPDATE federation_inbox SET attempts = attempts + 1 WHERE message_id = ?').run(row.message_id); return true; } this.db.prepare('INSERT INTO federation_inbox (message_id,idempotency_key,received_at,status,attempts,last_error) VALUES (?,?,?,?,?,?)').run(messageId, idempotencyKey, timestamp(), 'received', 1, null); return false; }
  markProcessed(messageId: string): InboxRecord { return this.update(messageId, 'processed'); }
  markFailed(messageId: string, error: string): InboxRecord { const record = this.update(messageId, 'failed', error); return record; }
  cleanup(before: number): number { return this.db.prepare('DELETE FROM federation_inbox WHERE received_at < ?').run(new Date(before).toISOString()).changes; }
  list(): InboxRecord[] { return (this.db.prepare('SELECT * FROM federation_inbox ORDER BY received_at').all() as InboxRow[]).map((row) => this.fromRow(row)); }
  private update(messageId: string, status: InboxRecord['status'], error?: string): InboxRecord { const result = this.db.prepare('UPDATE federation_inbox SET status = ?, last_error = ? WHERE message_id = ?').run(status, error ?? null, messageId); if (!result.changes) throw new Error(`Unknown inbox message: ${messageId}`); const row = this.db.prepare('SELECT * FROM federation_inbox WHERE message_id = ?').get(messageId) as InboxRow; return this.fromRow(row); }
  private fromRow(row: InboxRow): InboxRecord { return { messageId: row.message_id, idempotencyKey: row.idempotency_key, receivedAt: row.received_at, status: row.status, attempts: row.attempts, ...(row.last_error ? { lastError: row.last_error } : {}) }; }
}
