import assert from 'node:assert/strict';
import { test } from 'node:test';
import { FederationCoordinator, HmacMessageSigner, HmacMessageVerifier, InMemoryFederationNetwork, MemoryReplayStore, NodeRegistry, createFederationMessage, DistributedLeaseManager } from '../packages/federation/src/index.js';
import type { FederationMessage } from '../packages/federation/src/index.js';

const wait = async (milliseconds = 10): Promise<void> => new Promise((resolve) => setTimeout(resolve, milliseconds));
function node(id: string, capabilities: string[] = ['analysis', 'coding', 'testing', 'review']): { id: string; name: string; endpoint: string; role: 'hybrid'; capabilities: string[]; status: 'healthy'; trustLevel: 'TRUSTED' } { return { id, name: id, endpoint: `in-memory://${id}`, role: 'hybrid', capabilities, status: 'healthy', trustLevel: 'TRUSTED' }; }
function pair(): { a: FederationCoordinator; b: FederationCoordinator; registry: NodeRegistry; network: InMemoryFederationNetwork } { const registry = new NodeRegistry(); const network = new InMemoryFederationNetwork(); const signerA = new HmacMessageSigner('m14-test-key'); const signerB = new HmacMessageSigner('m14-test-key'); const a = new FederationCoordinator({ localNode: node('node-a'), registry, network, signer: signerA, verifier: new HmacMessageVerifier('m14-test-key') }); const b = new FederationCoordinator({ localNode: node('node-b'), registry, network, signer: signerB, verifier: new HmacMessageVerifier('m14-test-key') }); return { a, b, registry, network }; }
function task(taskId: string, capabilities: string[] = ['coding']): { taskId: string; requiredCapabilities: string[]; securityContext: { subject: string; permissions: string[]; trustLevel: 'TRUSTED' }; authorizationContext: Record<string, string> } { return { taskId, requiredCapabilities: capabilities, securityContext: { subject: 'test-operator', permissions: ['federation:dispatch'], trustLevel: 'TRUSTED' }, authorizationContext: { subject: 'test-operator', purpose: 'test' } }; }

 test('M14 node registration preserves identity, capabilities, trust, and lifecycle', () => { const registry = new NodeRegistry(); const registered = registry.registerNode(node('node-a', ['analysis'])); assert.equal(registered.id, 'node-a'); assert.deepEqual(registry.getNode('node-a').capabilities, ['analysis']); assert.equal(registry.getNode('node-a').status, 'healthy'); });
 test('M14 heartbeat refreshes a node and restores a degraded state', () => { const registry = new NodeRegistry(); registry.registerNode({ ...node('node-a'), status: 'joining' }); assert.equal(registry.heartbeat('node-a').status, 'healthy'); });
 test('M14 stale node detection marks nodes offline without deleting membership', () => { let now = Date.now(); const registry = new NodeRegistry({ heartbeatTimeoutMs: 100, clock: () => now }); registry.registerNode(node('node-a')); now += 101; assert.equal(registry.listNodes()[0]!.status, 'offline'); assert.equal(registry.getNode('node-a').id, 'node-a'); });
 test('M14 node selection is capability-aware and excludes unhealthy nodes', () => { const registry = new NodeRegistry(); registry.registerNode(node('good', ['coding'])); registry.registerNode({ ...node('bad', ['coding']), status: 'degraded' }); assert.deepEqual(registry.selectHealthyNodes(['coding']).map((candidate) => candidate.id), ['good']); });
 test('M14 federation router prefers local execution when eligible', () => { const { a, b } = pair(); const decision = a.route({ ...task('route-local'), locality: 'any' }); assert.equal(decision.nodeId, 'node-a'); assert.equal(decision.remote, false); b.registry.setHealth('node-b', { load: 1 }); });
 test('M14 distributed lease acquisition prevents duplicate ownership', () => { const leases = new DistributedLeaseManager(); const first = leases.acquire('task-1', 'node-a'); assert.ok(first); assert.equal(leases.acquire('task-1', 'node-b'), undefined); });
 test('M14 distributed lease renewal extends a valid lease', () => { let now = 1_000; const leases = new DistributedLeaseManager({ clock: () => now, defaultTtlMs: 100 }); const lease = leases.acquire('task-1', 'node-a')!; now = 1_050; const renewed = leases.renew(lease.leaseId, lease.fencingToken); assert.equal(renewed.expiresAt, 1_150); });
 test('M14 lease expiration is explicit and measurable', () => { let now = 1_000; const leases = new DistributedLeaseManager({ clock: () => now, defaultTtlMs: 100 }); leases.acquire('task-1', 'node-a'); now = 1_101; assert.equal(leases.expire().length, 1); assert.equal(leases.list()[0]!.status, 'expired'); });
 test('M14 fencing tokens reject stale completion after lease replacement', () => { let now = 1_000; const leases = new DistributedLeaseManager({ clock: () => now, defaultTtlMs: 100 }); const old = leases.acquire('task-1', 'node-a')!; now = 1_101; leases.expire(); const next = leases.acquire('task-1', 'node-b')!; assert.equal(next.fencingToken > old.fencingToken, true); assert.equal(leases.isValid(next.leaseId, old.fencingToken), false); });
 test('M14 signed messages verify with injected deterministic keys', () => { const signer = new HmacMessageSigner('test-key'); const verifier = new HmacMessageVerifier('test-key'); const message = createFederationMessage({ type: 'heartbeat', sourceNodeId: 'node-a', destinationNodeId: 'node-b', payload: { ok: true } }, signer); assert.equal(verifier.verify(message), true); });
 test('M14 invalid signatures are rejected', () => { const signer = new HmacMessageSigner('test-key'); const verifier = new HmacMessageVerifier('test-key'); const message = createFederationMessage({ type: 'heartbeat', sourceNodeId: 'node-a', payload: { ok: true } }, signer); const invalid = { ...message, signature: '0'.repeat(64) }; assert.equal(verifier.verify(invalid), false); });
 test('M14 replay protection rejects the same message ID twice', () => { const signer = new HmacMessageSigner('test-key'); const verifier = new HmacMessageVerifier('test-key'); const message = createFederationMessage({ type: 'heartbeat', sourceNodeId: 'node-a', payload: { ok: true } }, signer); assert.equal(verifier.verify(message), true); assert.equal(verifier.verify(message), false); });
 test('M14 unknown schema versions are rejected', () => { const signer = new HmacMessageSigner('test-key'); const verifier = new HmacMessageVerifier('test-key'); const message = createFederationMessage({ type: 'heartbeat', sourceNodeId: 'node-a', payload: { ok: true } }, signer); const unknown = { ...message, schemaVersion: 99 } as unknown as FederationMessage; assert.equal(verifier.verify(unknown), false); });
 test('M14 remote task dispatch preserves correlation, trace, capabilities, and context', async () => { const { a, b } = pair(); const dispatched = await a.dispatch({ ...task('remote-1'), nodeId: 'node-b', correlationId: 'corr-1', traceId: 'trace-1' }); await wait(); const accepted = b.getTask('remote-1'); assert.equal(dispatched.local, false); assert.equal(accepted.correlationId, 'corr-1'); assert.equal(accepted.traceId, 'trace-1'); assert.deepEqual(accepted.requiredCapabilities, ['coding']); });
 test('M14 remote task completion returns signed evidence to the source node', async () => { const { a, b } = pair(); await a.dispatch({ ...task('remote-2'), nodeId: 'node-b' }); await wait(); await b.complete('remote-2', true); await wait(); assert.equal(a.getTask('remote-2').status, 'completed'); });
 test('M14 remote task failure returns an explicit failure state', async () => { const { a, b } = pair(); await a.dispatch({ ...task('remote-3'), nodeId: 'node-b' }); await wait(); await b.complete('remote-3', false, 'worker failed'); await wait(); assert.equal(a.getTask('remote-3').status, 'failed'); assert.equal(a.getTask('remote-3').error, 'worker failed'); });
 test('M14 worker-node disappearance is retained as offline membership', () => { const { a, registry } = pair(); registry.markOffline('node-b'); assert.equal(a.getNode('node-b').status, 'offline'); assert.equal(a.listNodes().length, 2); });
 test('M14 failed remote task can be reassigned to another eligible node', async () => { const { a, registry } = pair(); registry.markOffline('node-b'); const local = await a.dispatch({ ...task('reassign-1'), nodeId: 'node-a' }); const reassigned = await a.handoff(local.taskId, 'node-a'); assert.equal(reassigned.nodeId, 'node-a'); assert.equal(reassigned.status, 'reassigned'); });
 test('M14 federated swarm can add nodes, delegate, aggregate, and stop', async () => { const { a } = pair(); const swarm = a.createSwarm({ name: 'federated-test' }); a.addNode(swarm.id, 'node-b'); const record = await a.delegateSwarm(swarm.id, { ...task('swarm-task'), nodeId: 'node-a' }); const result = a.aggregate(swarm.id, [{ taskId: record.taskId, nodeId: 'node-a', success: true, score: 0.9, fencingToken: record.fencingToken ?? 0 }]); assert.equal(result.success, true); assert.equal((await a.stopSwarm(swarm.id)).state, 'stopped'); });
 test('M14 trust boundaries expose no inherited local privileges', () => { const { a } = pair(); const trust = a.registry.inspectTrust('node-b'); assert.deepEqual(trust.inheritedLocalPrivileges, []); assert.equal(trust.trustLevel, 'TRUSTED'); });
 test('M14 authorization context is preserved across remote dispatch', async () => { const { a } = pair(); const result = await a.dispatch({ ...task('auth-1'), nodeId: 'node-b', securityContext: { subject: 'alice', permissions: ['federation:dispatch', 'task:read'], trustLevel: 'LIMITED' }, authorizationContext: { subject: 'alice', approvalId: 'approval-1' } }); assert.equal(result.authorizationContext.subject, 'alice'); assert.equal(result.authorizationContext.approvalId, 'approval-1'); });
 test('M14 100-agent multi-node simulation remains bounded and deterministic', () => { const registry = new NodeRegistry(); const capabilities = ['analysis', 'coding', 'testing', 'review']; for (let nodeIndex = 0; nodeIndex < 5; nodeIndex += 1) registry.registerNode(node(`sim-${nodeIndex}`, capabilities)); const selected = new Set<string>(); for (let taskIndex = 0; taskIndex < 100; taskIndex += 1) selected.add(registry.selectHealthyNodes([capabilities[taskIndex % capabilities.length]!] )[taskIndex % 5]!.id); assert.equal(selected.size, 5); assert.equal(registry.listNodes().length, 5); });
 test('M14 deterministic network failure becomes an explicit dispatch failure', async () => { const { a } = pair(); await a.transport.close(); await assert.rejects(() => a.dispatch({ ...task('network-failure'), nodeId: 'node-b' }), /closed/); });
 test('M14 duplicate transport messages do not duplicate remote task state', async () => { const { a, b } = pair(); const signer = new HmacMessageSigner('m14-test-key'); const message = createFederationMessage({ type: 'task.submit', sourceNodeId: 'node-a', destinationNodeId: 'node-b', correlationId: 'duplicate-corr', traceId: 'duplicate-trace', payload: { taskId: 'duplicate-task', correlationId: 'duplicate-corr', traceId: 'duplicate-trace', priority: 1, requiredCapabilities: ['coding'], securityContext: task('x').securityContext, authorizationContext: { sourceNodeId: 'node-a' } } }, signer); await a.transport.send(message); await a.transport.send(message); await wait(); assert.equal(b.listTasks().filter((record) => record.taskId === 'duplicate-task').length, 1); assert.equal(b.metrics().signatureFailures + b.metrics().replayRejections > 0, true); });
 test('M14 metrics report nodes, local/remote tasks, leases, and security failures', async () => { const { a } = pair(); await a.dispatch({ ...task('metrics-1'), nodeId: 'node-a' }); const metrics = a.metrics(); assert.equal(metrics.nodesTotal, 2); assert.equal(metrics.localTasks, 1); assert.equal(metrics.remoteTasks, 0); assert.equal(typeof metrics.leaseConflicts, 'number'); });
 test('M14 replay store purges expired message IDs deterministically', () => { const store = new MemoryReplayStore(); store.remember('message-1', 10); assert.equal(store.has('message-1'), true); store.purge(11); assert.equal(store.has('message-1'), false); });
