import { id } from '../../core/src/index.js';
import { buildAgentContext } from './context.js';
import { BudgetTracker } from './budget.js';
import { AgentRuntimeError, normalizeAgentError } from './errors.js';
import { AgentToolExecutor } from './tool-executor.js';
import type { AgentRuntimeConfig, AgentRuntimeHost, AgentExecutionResult, AgentProviderResponse, AgentTaskInput, AgentContext } from './types.js';
import { defaultAgentBudget, isStructuredProvider } from './types.js';
import type { AgentToolRegistry } from './tool-registry.js';

export class AgentToolCallingLoop {
  constructor(private readonly host: AgentRuntimeHost, private readonly registry: AgentToolRegistry) {}

  async run(input: AgentTaskInput, config: AgentRuntimeConfig = {}): Promise<AgentExecutionResult> {
    const started = Date.now(); const traceId = id('agent-trace'); const budget = new BudgetTracker(defaultAgentBudget(config)); const tools = this.registry.list(); const calls: AgentExecutionResult['toolCalls'] = []; const errors: string[] = []; const seenCalls = new Map<string, number>(); let output: string | undefined; let status: AgentExecutionResult['status'] = 'failed'; let providerName = this.host.provider.name; let model: string | undefined; let memoriesRecalled = 0; let memoriesCreated = 0;
    const budgetSignals = new Set<string>(); const emitBudgetSignals = async () => { const state = budget.status(); const limits: Array<[string, number, number]> = [['iterations', state.iterations, budget.budget.maxIterations], ['toolCalls', state.toolCalls, budget.budget.maxToolCalls], ['providerCalls', state.providerCalls, budget.budget.maxProviderCalls], ['tokens', state.tokens, budget.budget.maxTokens], ['costUsd', state.costUsd, budget.budget.maxCostUsd], ['memoryRecalls', state.memoryRecalls, budget.budget.maxMemoryRecalls]]; for (const [name, used, limit] of limits) { if (limit > 0 && used / limit >= 0.8 && !budgetSignals.has(`warning:${name}`)) { budgetSignals.add(`warning:${name}`); await this.event('agent.budget.warning', input, traceId, { resource: name, used, limit }); } } for (const exceeded of state.exceeded) if (!budgetSignals.has(`exceeded:${exceeded}`)) { budgetSignals.add(`exceeded:${exceeded}`); await this.event('agent.budget.exceeded', input, traceId, { resource: exceeded }); } }; const abort = new AbortController(); const external = config.signal ?? input.signal; const forward = () => abort.abort(); if (external) { if (external.aborted) abort.abort(); else external.addEventListener('abort', forward, { once: true }); } const timer = setTimeout(() => abort.abort(), budget.budget.maxExecutionTimeMs);
    await this.event('agent.created', input, traceId, { role: this.host.agents.get(input.agentId).role });
    try {
      const context = await buildAgentContext(this.host, input, tools, budget, config); memoriesRecalled = context.memories.length; await emitBudgetSignals(); await this.event('agent.context.created', input, traceId, { memoryCount: memoriesRecalled, toolCount: tools.length }); if (memoriesRecalled) await this.event('agent.memory.recalled', input, traceId, { memoryCount: memoriesRecalled });
      while (!output) {
        if (abort.signal.aborted) throw new AgentRuntimeError(external?.aborted ? 'cancelled' : 'timeout', external?.aborted ? 'agent execution cancelled' : 'agent execution timed out', external?.aborted ? false : true);
        budget.assertIterationAllowed(); budget.iteration(); budget.assertProviderAllowed(); budget.providerCall(); await this.event('agent.provider.started', input, traceId, { iteration: budget.iterationsCount, provider: providerName });
        const response = await this.decide(input, context, budget, abort.signal); if (abort.signal.aborted) throw new AgentRuntimeError(external?.aborted ? 'cancelled' : 'timeout', external?.aborted ? 'agent execution cancelled' : 'agent execution timed out', external?.aborted ? false : true); providerName = this.host.provider.name; model = response.usage?.model ?? model; budget.usage(response.usage?.tokens ?? 0, response.usage?.costUsd ?? 0); await emitBudgetSignals(); await this.event('agent.provider.completed', input, traceId, { iteration: budget.iterationsCount, provider: providerName, model, tokens: response.usage?.tokens ?? 0 });
        const decision = validateDecision(response); await this.event('agent.decision.created', input, traceId, { iteration: budget.iterationsCount, type: decision.type });
        if (decision.type === 'final') { output = sanitizeText(decision.content); status = 'completed'; await this.event('agent.completed', input, traceId, { iteration: budget.iterationsCount, output: sanitizeText(output) }); break; }
        const signature = `${decision.toolName}:${JSON.stringify(decision.arguments)}`; const repetitions = (seenCalls.get(signature) ?? 0) + 1; seenCalls.set(signature, repetitions); if (repetitions > budget.budget.repeatedToolCallLimit) throw new AgentRuntimeError('repeated-tool-call', `repeated identical tool call: ${decision.toolName}`, false);
        budget.assertToolAllowed(); budget.toolCall(); await emitBudgetSignals();         const call = await new AgentToolExecutor(this.host, this.registry).execute(input, decision.toolName, decision.arguments, budget.iterationsCount, abort.signal); calls.push(call); if (call.status === 'denied') { budget.policyDenied(); await this.event('agent.policy.denied', input, traceId, { tool: decision.toolName, reason: call.error }); throw new AgentRuntimeError('policy-denied', call.error ?? 'tool policy denied', false); }
        context.history.push({ role: 'assistant', content: JSON.stringify({ type: 'tool_call', toolName: decision.toolName, arguments: sanitizeObject(decision.arguments) }) }); context.history.push({ role: 'tool', toolCallId: call.toolCallId, content: JSON.stringify(sanitizeObject({ status: call.status, result: call.result, error: call.error })) });
        if (call.status === 'cancelled') throw new AgentRuntimeError('cancelled', call.error ?? 'agent execution cancelled', false); if (call.status === 'timeout') throw new AgentRuntimeError('timeout', call.error ?? 'tool execution timed out', true); if (call.status === 'failed') throw new AgentRuntimeError(/invalid|missing|required|field .* must be/i.test(call.error ?? '') ? 'invalid-tool-arguments' : 'unknown', call.error ?? 'tool execution failed', false);
        await this.event('agent.iteration.completed', input, traceId, { iteration: budget.iterationsCount, toolCalls: calls.length });
      }
    } catch (error) { const normalized = abort.signal.aborted ? new AgentRuntimeError(external?.aborted ? 'cancelled' : 'timeout', external?.aborted ? 'agent execution cancelled' : 'agent execution timed out', external?.aborted ? false : true) : normalizeAgentError(error); errors.push(sanitizeText(normalized.message)); status = normalized.kind === 'cancelled' ? 'cancelled' : normalized.kind === 'timeout' ? 'timeout' : normalized.kind === 'budget-exceeded' || normalized.kind === 'repeated-tool-call' ? 'budget_exceeded' : normalized.kind === 'policy-denied' || normalized.kind === 'authorization-denied' || normalized.kind === 'sandbox-denied' || normalized.kind === 'invalid-tool-arguments' ? 'policy_denied' : 'failed'; await this.event(status === 'cancelled' ? 'agent.cancelled' : status === 'timeout' ? 'agent.timeout' : 'agent.failed', input, traceId, { error: sanitizeText(normalized.message), retryable: normalized.retryable }); }
    finally { clearTimeout(timer); if (external) external.removeEventListener('abort', forward); const elapsed = Date.now() - started; await this.event('agent.evaluation.completed', input, traceId, { status, durationMs: elapsed, toolCalls: calls.length, iterations: budget.iterationsCount }); try { memoriesCreated = await this.host.recordLearning({ executionId: input.executionId, taskId: input.taskId, taskType: input.title.toLowerCase().replaceAll(' ', '-'), agentId: input.agentId, capabilities: this.host.agents.get(input.agentId).capabilities, success: status === 'completed', quality: status === 'completed' ? 0.75 : 0, executionTimeMs: elapsed, attempts: 1, ...(output ? { output: sanitizeText(output) } : {}), ...(errors[0] ? { error: errors[0] } : {}), ...(input.sessionId ? { sessionId: input.sessionId } : {}), ...(input.swarmId ? { swarmId: input.swarmId } : {}), metadata: { traceId, toolCalls: calls.length, iterations: budget.iterationsCount } }); await this.event('agent.learning.updated', input, traceId, { memoriesCreated }); } catch (learningError) { errors.push(`learning persistence failed: ${sanitizeText(learningError instanceof Error ? learningError.message : String(learningError))}`); } }
    return { executionId: input.executionId, taskId: input.taskId, agentId: input.agentId, status, ...(output !== undefined ? { output } : {}), toolCalls: calls, iterations: budget.iterationsCount, durationMs: Date.now() - started, provider: providerName, ...(model ? { model } : {}), usage: { tokens: budget.status().tokens, costUsd: budget.status().costUsd }, memoriesRecalled, memoriesCreated, errors, traceId, budget: budget.status() };
  }

  private async decide(input: AgentTaskInput, context: AgentContext, budget: BudgetTracker, signal: AbortSignal): Promise<AgentProviderResponse> {
    if (isStructuredProvider(this.host.provider)) return this.host.provider.executeAgent({ goal: input.goal, task: context.task, agent: context.agent, context, tools: context.tools, iteration: budget.iterationsCount, signal });
    const result = await this.host.provider.execute({ goal: input.goal, task: { id: input.taskId, title: input.title, description: input.description } as never, agent: context.agent.name });
    return { decision: { type: 'final', content: typeof result.output === 'string' ? result.output : JSON.stringify(result.output) }, usage: { tokens: result.tokens, costUsd: result.costUsd } };
  }

  private async event(type: string, input: AgentTaskInput, traceId: string, payload: Record<string, unknown>): Promise<void> { await this.host.appendEvent({ type, executionId: input.executionId, taskId: input.taskId, agentId: input.agentId, payload: { traceId, ...payload } }); }
}

function validateDecision(response: AgentProviderResponse): AgentProviderResponse['decision'] { const decision = response?.decision; if (!decision || typeof decision !== 'object' || !('type' in decision)) throw new AgentRuntimeError('malformed-decision', 'provider returned a malformed agent decision', false); if (decision.type === 'final' && typeof decision.content === 'string') return decision; if (decision.type === 'tool_call' && typeof decision.toolName === 'string' && decision.arguments && typeof decision.arguments === 'object' && !Array.isArray(decision.arguments)) return { type: 'tool_call', toolName: decision.toolName, arguments: decision.arguments as Record<string, unknown> }; throw new AgentRuntimeError('malformed-decision', 'provider returned an invalid agent decision', false); }
function sanitizeText(value: string): string { return value.replace(/(Bearer\s+)[^\s]+/gi, '$1[REDACTED]').replace(/(sk-[A-Za-z0-9_-]{8,})/g, '[REDACTED]').replace(/((?:token|password|secret|api[_-]?key|authorization)\s*[:=]\s*)[^\s,;]+/gi, '$1[REDACTED]').slice(0, 8_192); }
function sanitizeObject(value: unknown): unknown { if (Array.isArray(value)) return value.map(sanitizeObject); if (!value || typeof value !== 'object') return value; const output: Record<string, unknown> = {}; for (const [key, item] of Object.entries(value)) output[key] = /(secret|token|password|api[_-]?key|authorization|private[_-]?key|stdin)/i.test(key) ? '[REDACTED]' : sanitizeObject(item); return output; }
