import { id } from '../../core/src/index.js';
import { AgentRuntimeError, normalizeAgentError } from './errors.js';
import type { AgentRuntimeHost, AgentTaskInput, AgentToolDefinition, ToolCallRecord } from './types.js';
import type { AgentToolRegistry } from './tool-registry.js';

export class AgentToolExecutor {
  constructor(private readonly host: AgentRuntimeHost, private readonly registry: AgentToolRegistry) {}

  async execute(input: AgentTaskInput, toolName: string, args: Record<string, unknown>, iteration: number, signal: AbortSignal): Promise<ToolCallRecord> {
    const toolCallId = id('tool-call'); const started = Date.now();
    let tool: AgentToolDefinition | undefined;
    try { tool = this.registry.get(toolName); } catch (error) { return this.failed(toolCallId, input, iteration, toolName, args, started, 'low', 'READ', 'tool-not-found', error); }
    const validation = this.registry.validate(toolName, args);
    if (validation.length) return this.failed(toolCallId, input, iteration, toolName, args, started, tool.risk, tool.category, 'invalid-tool-arguments', new Error(validation.join('; ')));
    const agent = this.host.agents.get(input.agentId);
    const permissionsAllowed = tool.permissions.every((permission) => agent.permissions.includes(permission) || agent.permissions.includes('*'));
    if (!permissionsAllowed) return this.denied(toolCallId, input, iteration, tool, args, started, `agent ${input.agentId} lacks required tool permission`);
    if (signal.aborted) return this.cancelled(toolCallId, input, iteration, tool, args, started);
    let authorization: { allowed: boolean; reason: string; approvalId?: string };
    try { authorization = await this.host.requestTool({ id: toolCallId, executionId: input.executionId, agentId: input.agentId, tool: tool.name, input: args, risk: tool.risk }); } catch (error) { return this.failed(toolCallId, input, iteration, tool.name, args, started, tool.risk, tool.category, 'policy-denied', error); }
    if (!authorization.allowed) { await this.host.appendEvent({ type: 'agent.tool.denied', executionId: input.executionId, taskId: input.taskId, agentId: input.agentId, payload: { toolCallId, tool: tool.name, risk: tool.risk, reason: authorization.reason, approvalId: authorization.approvalId } }); return { toolCallId, iteration, agentId: input.agentId, taskId: input.taskId, executionId: input.executionId, toolName: tool.name, arguments: safeArgs(args), durationMs: Date.now() - started, risk: tool.risk, category: tool.category, authorization, status: 'denied', error: authorization.reason }; }
    const timeoutMs = Math.max(1, Math.floor(tool.timeoutMs ?? 30_000)); const timeout = new AbortController(); const timer = setTimeout(() => timeout.abort(), timeoutMs); const combined = AbortSignal.any([signal, timeout.signal]);
    await this.host.appendEvent({ type: 'agent.tool.authorized', executionId: input.executionId, taskId: input.taskId, agentId: input.agentId, payload: { toolCallId, iteration, tool: tool.name, risk: tool.risk, category: tool.category, authorization: { allowed: authorization.allowed, reason: authorization.reason } } });
    await this.host.appendEvent({ type: 'agent.tool.requested', executionId: input.executionId, taskId: input.taskId, agentId: input.agentId, payload: { toolCallId, iteration, tool: tool.name, risk: tool.risk, category: tool.category, authorization: { allowed: authorization.allowed, reason: authorization.reason } } });
    await this.host.appendEvent({ type: 'agent.tool.started', executionId: input.executionId, taskId: input.taskId, agentId: input.agentId, payload: { toolCallId, iteration, tool: tool.name } });
    try { const result = await tool.execute(args, { agentId: input.agentId, taskId: input.taskId, executionId: input.executionId, iteration, signal: combined }); const record: ToolCallRecord = { toolCallId, iteration, agentId: input.agentId, taskId: input.taskId, executionId: input.executionId, toolName: tool.name, arguments: safeArgs(args), durationMs: Date.now() - started, risk: tool.risk, category: tool.category, authorization, status: 'completed', result: sanitize(result) }; await this.host.appendEvent({ type: 'agent.tool.completed', executionId: input.executionId, taskId: input.taskId, agentId: input.agentId, payload: { ...record, result: sanitize(result) } }); return record; } catch (error) { const normalized = normalizeAgentError(error); const status: ToolCallRecord['status'] = combined.aborted ? (timeout.signal.aborted && !signal.aborted ? 'timeout' : 'cancelled') : 'failed'; const record: ToolCallRecord = { toolCallId, iteration, agentId: input.agentId, taskId: input.taskId, executionId: input.executionId, toolName: tool.name, arguments: safeArgs(args), durationMs: Date.now() - started, risk: tool.risk, category: tool.category, authorization, status, error: normalized.message }; await this.host.appendEvent({ type: status === 'timeout' ? 'agent.tool.timeout' : status === 'cancelled' ? 'agent.tool.cancelled' : 'agent.tool.failed', executionId: input.executionId, taskId: input.taskId, agentId: input.agentId, payload: { ...record } }); return record; } finally { clearTimeout(timer); }
  }

  private denied(toolCallId: string, input: AgentTaskInput, iteration: number, tool: AgentToolDefinition, args: Record<string, unknown>, started: number, reason: string): ToolCallRecord { return { toolCallId, iteration, agentId: input.agentId, taskId: input.taskId, executionId: input.executionId, toolName: tool.name, arguments: safeArgs(args), durationMs: Date.now() - started, risk: tool.risk, category: tool.category, authorization: { allowed: false, reason }, status: 'denied', error: reason }; }
  private cancelled(toolCallId: string, input: AgentTaskInput, iteration: number, tool: AgentToolDefinition, args: Record<string, unknown>, started: number): ToolCallRecord { return { toolCallId, iteration, agentId: input.agentId, taskId: input.taskId, executionId: input.executionId, toolName: tool.name, arguments: safeArgs(args), durationMs: Date.now() - started, risk: tool.risk, category: tool.category, authorization: { allowed: false, reason: 'agent execution cancelled' }, status: 'cancelled', error: 'agent execution cancelled' }; }
  private failed(toolCallId: string, input: AgentTaskInput, iteration: number, toolName: string, args: Record<string, unknown>, started: number, risk: AgentToolDefinition['risk'], category: AgentToolDefinition['category'], kind: AgentRuntimeError['kind'], error: unknown): ToolCallRecord { const normalized = error instanceof AgentRuntimeError ? error : new AgentRuntimeError(kind, error instanceof Error ? error.message : String(error), false, error); return { toolCallId, iteration, agentId: input.agentId, taskId: input.taskId, executionId: input.executionId, toolName, arguments: safeArgs(args), durationMs: Date.now() - started, risk, category, authorization: { allowed: false, reason: normalized.message }, status: 'failed', error: normalized.message }; }
}

function safeArgs(args: Record<string, unknown>): Record<string, unknown> { return sanitize(args); }
function sanitize(value: unknown): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) return { value }; const output: Record<string, unknown> = {}; for (const [key, item] of Object.entries(value)) output[key] = /(secret|token|password|api[_-]?key|authorization|private[_-]?key|stdin)/i.test(key) ? '[REDACTED]' : item && typeof item === 'object' ? sanitize(item) : item; return output; }
